---
# - name: check if lazydocker is installed
#   shell: command -v lazydocker
#   register: lazydocker_exists
#   ignore_errors: true
#
# - name: check if go is installed
#   shell: command -v go
#   register: go_exists
#   ignore_errors: true
#

- name: install golang
  become: true
  package:
    name: go
    state: present
#
- name: Install
  become: true
  kewlfft.aur.aur:
    name:
      - lazydocker
