---
- hosts: all
  # - hosts: localhost
  # connection: local
  vars_files:
    - ./vars/localhost.yml

  roles:
    - { role: pacman, become: true }
    - { role: nvim-build, become: true }
    - nvim-config
    - rust
    - volta
    - tmux
    - zsh
    - golang
    - cargo
    - docker
    - aur
    - python
    - snap
