---
- name: check if volta is installed
  stat: "{{ansible_user_dir}}/.volta/bin/volta"
  register: volta_exists
  ignore_errors: true
  tags: volta

- name: Download installer
  when: volta_exists is failed
  get_url:
    url: https://get.volta.sh
    dest: /tmp/volta.sh
    mode: "0755"
    force: "yes"
  tags: volta

- name: install volta
  when: volta_exists is failed
  shell: /tmp/volta.sh
  tags: volta
- name: install node
  shell: "{{ansible_user_dir}}/.volta/bin/volta install node"
  become_user: adgai
  tags: volta
