---
- name: full system upgrade
  tags: packages
  pacman:
    update_cache: yes
    upgrade: yes
- name: install mcfly
  tags: packages
  package:
    name:
      - mcfly
    state: latest

- name: install yay
  tags: packages
  package:
    name: yay
    state: latest

# - name: install mirror tools
#   tags: packages
#   package:
#     name:
#       - reflector
#       - rsync
#       - curl
#
#   state: present

# - name: update mirrors
#   tags: packages
#   become: true
#   shell: reflector --latest 5 --sort rate --save /etc/pacman.d/mirrorlist

- name: install pass
  tags: packages
  package:
    name: pass
    state: latest
